In [1]:
import numpy as np
import pandas as pd


In [2]:
data = pd.read_csv("iris.csv")
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [3]:
data.shape

(150, 6)

In [4]:
data['Species'].value_counts()
# memagin species warga wala count eka labee

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [6]:
data.describe()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667
std,43.445368,0.828066,0.433594,1.764420,0.763161
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000


In [7]:
x = data.iloc[:,1:5]
# ithatha eke adahasa => iloc = "index location" , : => okkoma rows tika ganna  ,  1:5 => 1  ha 5 wenakm columns tika ganna(1,2,3,4 columns tika)
x

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [8]:
y = data.iloc[:,-1]
# -1 yanu anthima column ekai
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [17]:
# x values tika feature scaling kala yuthuya

x = scaler.fit_transform(x)
x


array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [24]:
 from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [25]:
x_train.shape

(120, 4)

In [26]:
x_test.shape

(30, 4)

In [27]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 1)
model.fit(x_train,y_train)
# n_neighbors = 1 yanu 'k' value ekai


KNeighborsClassifier(n_neighbors=1)

In [28]:
pred = model.predict(x_test)

In [29]:
pred


array(['Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [31]:
y_test

21         Iris-setosa
88     Iris-versicolor
34         Iris-setosa
72     Iris-versicolor
105     Iris-virginica
140     Iris-virginica
41         Iris-setosa
125     Iris-virginica
98     Iris-versicolor
102     Iris-virginica
133     Iris-virginica
110     Iris-virginica
149     Iris-virginica
32         Iris-setosa
17         Iris-setosa
148     Iris-virginica
45         Iris-setosa
131     Iris-virginica
40         Iris-setosa
137     Iris-virginica
126     Iris-virginica
122     Iris-virginica
4          Iris-setosa
138     Iris-virginica
54     Iris-versicolor
33         Iris-setosa
48         Iris-setosa
22         Iris-setosa
53     Iris-versicolor
58     Iris-versicolor
Name: Species, dtype: object

In [34]:
# accuracy eka check kiriima 
from sklearn.metrics import accuracy_score
accuracy =  accuracy_score(y_test,pred)
accuracy

0.9333333333333333

In [36]:
# accuracy eka confution matrix eken check kiriima

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,pred)
cm

array([[11,  0,  0],
       [ 0,  5,  1],
       [ 0,  1, 12]])

In [40]:
# result eka display kara ganiima
# data tika columns widiyata one nisa transpose karai

result = pd.DataFrame(data = [y_test.values,pred], index = ['y_test','pred'])
result.transpose()


,y_test,pred
0,Iris-setosa,Iris-setosa
1,Iris-versicolor,Iris-versicolor
2,Iris-setosa,Iris-setosa
3,Iris-versicolor,Iris-virginica
4,Iris-virginica,Iris-virginica
5,Iris-virginica,Iris-virginica
6,Iris-setosa,Iris-setosa
7,Iris-virginica,Iris-virginica
8,Iris-versicolor,Iris-versicolor
9,Iris-virginica,Iris-virginica


In [41]:
# hari giya values tika
correct_sum = []
for i in range(1,20):
    model = KNeighborsClassifier(n_neighbors = i)
    model.fit(x_train,y_train)
    pred = model.predict(x_test)
    correct =np.sum(pred == y_test)
    correct_sum.append(correct)
    

In [42]:
correct_sum

[np.int64(28),
 np.int64(26),
 np.int64(25),
 np.int64(26),
 np.int64(26),
 np.int64(27),
 np.int64(26),
 np.int64(26),
 np.int64(26),
 np.int64(26),
 np.int64(26),
 np.int64(27),
 np.int64(26),
 np.int64(26),
 np.int64(27),
 np.int64(27),
 np.int64(26),
 np.int64(27),
 np.int64(27)]

In [43]:
result = pd.DataFrame(data == correct_sum)
result.index = result.index + 1
result.T

ValueError: Unable to coerce to Series, length must be 6: given 19

In [44]:
model = KNeighborsClassifier(n_neighbors = 8)
model.fit(x_train,y_train)
pred = model.predict(x_test)

In [45]:
accuracy_score(y_test,pred)

0.8666666666666667

In [47]:
confusion_matrix(y_test,pred)

array([[11,  0,  0],
       [ 0,  5,  1],
       [ 0,  3, 10]])