In [1]:
import numpy as np
from sklearn.model_selection import train_test_split 

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
y = np.array([0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1])

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25 ) #mehidii labadena data set eken x haa y wala tarin and test values tika ganna puluwan. 
#ewa dala thiyena variable wala piliwelatama alabee
# test_size eken wenne test and train kiriimata awashya data ganana wen kiriimai.(0 th 1 th athara gayak wiya yuthuya) 
# thawada ihatha train_test_split eka athulata "shuffle =False" lesa dunnama labena dat tika order ekakata labee. 

In [12]:
x_train

array([ 9, 17, 12,  8,  3, 16, 14, 15,  4,  7, 20,  5, 19,  6, 11])

In [13]:
len(x_train) # labadun data 20 n data 5k x eka train karanna labee (random agayan labee)

15

In [14]:
x_test

array([13,  1, 18,  2, 10])

In [15]:
len(x_test)  # labadun data 20 n data 5k  x eka test karanna labee

5

In [16]:
y_train

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [17]:
y_test

array([1, 0, 1, 0, 0])